---
title: "Qualitative Sub-Study Network Diagrams"
author: "Camille Hochheimer, PhD; Carlos Rodriguez, PhD"
date: "`r Sys.Date()`"
output: html_document
---


```{r, echo = FALSE, eval = FALSE}
# This script is designed to generate and upload 5 network diagrams for each 
# participant in the HSQ study. These diagrams are intended for use in the 
# qualitative sub-study.

# Dependencies:
# Requires API access to the HSQ Participant Management RedCap Project
# Requires the RedCap report ID 109108 titled ACTION: Needs Qualitative Diagrams

# Output:
# Generates 5 diagrams for each participant that are then uploaded back to the 
# RedCap project under the fields qual_diagram_1:5

# The presence of the uploaded diagrams is verified in RedCap report 109599
# which is then used to generate the qualitative dyad report.
```

```{r, load libraries, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

library(egor) #for diagrams
library(here) #for sharing this RProject
library(tidyverse) #for data wrangling
library(purrr) 
library(network) #for diagrams
library(ggplot2) #for diagrams
library(igraph) #for diagrams

library(ggraph)
library(tidygraph)
```


```{r, set token, include=FALSE}
# your API token
# set in environmental variables in Windows
# Token generated in RedCap once API access is granted
.token <- Sys.getenv("HSQ_api")
```


```{r, wrangle_pna, include=FALSE}
#function for wrangling PNA data
wrangle_pna <- function(pna, att_start, att_end, aa_start,
                        a1, a25,
                        namerange = 2:26, tierange = 502:801){
  
  pna2 <- pna %>% 
    rowwise() %>% 
    #get rid of people who didn't name an alter or any alter-alter ties
    dplyr::select(-starts_with("network_diagram_")) %>% 
    dplyr::filter(sum(is.na(across(all_of(namerange)))) == 0 &
                    sum(is.na(across(all_of(tierange))), na.rm = TRUE) == 0) %>%
    mutate(across(.cols = c(starts_with("alttobacco_a"), starts_with("altsmoke_a")),
                  ~case_when(.x == "Checked" ~ "Yes",
                             .x == "Unchecked" ~ "No")))
  
  et <- onefile_to_egor(egos = pna2,
                        ID.vars = list(ego = "record_id"),
                        # Name of Variable with the first alter attribute
                        attr.start.col = att_start,
                        # Name of variable with last alter attribute
                        attr.end.col = att_end, 
                        # Number of maximum alters that were named by participants
                        max.alters = 25, 
                        # Name of first alter-alter variable
                        aa.first.var = aa_start) 
  
  alter_filter2 <- et %>% 
    as_tibble() %>% 
    arrange(.egoID) %>% 
    select(eval(substitute(a1)):eval(substitute(a25))) %>% 
    mutate(across(.fns = ~ !is.na(.))) %>% 
    as.data.frame() %>% 
    tidyr::pivot_longer(cols = everything()) %>% 
    pull(value)
  
  e2 <- et %>% 
    activate(alter) %>% 
    filter(alter_filter2) %>% 
    activate(aatie) %>% 
    filter(weight != "")
  
  #add alter names to the alter data
  e2$alter$aname <- c(t(e2$ego[,2:26]))
  
  e2$aatie <- e2$aatie %>% 
    #show somewhat likely and very likely
    filter(weight != "Not at all likely")
  
  # This line was in Camille's baseline script.
  e2$aatie$weight2 <- ifelse(e2$aatie$weight == "Somewhat likely", 1, 3)

  # e2$aatie$weight2 <- ifelse(e2$aatie$weight == "Not at all likely", 0.01, #set to zero
  #                            ifelse(e2$aatie$weight == "Somewhat likely", 1, 2))

  # e2$aatie$weight2 <- ifelse(e2$aatie$weight == "Somewhat likely", 1, 2)
  #show just very likely
  #   filter(weight == "Very likely")
  # e2$aatie$weight2 <- 3
  
  return(e2)
}
```


```{r, mytriangle, include=FALSE}
# This section sets the triangle and circle shapes for the diagrams
#triangle vertex shape
mytriangle <- function(coords, v=NULL, params) {
  vertex.color <- params("vertex", "color")
  if (length(vertex.color) != 1 && !is.null(v)) {
    vertex.color <- vertex.color[v]
  }
  vertex.size <- 1/200 * params("vertex", "size")
  if (length(vertex.size) != 1 && !is.null(v)) {
    vertex.size <- vertex.size[v]
  }

  symbols(x=coords[,1], y=coords[,2], bg=vertex.color,
          stars=cbind(vertex.size, vertex.size, vertex.size),
          add=TRUE, inches=FALSE)
}

# clips as a circle
add_shape("triangle", clip=shapes("circle")$clip,
          plot=mytriangle)

#factor with case_when
fct_case_when <- function (...){
  args <- as.list(match.call())
  levels <- sapply(args[-1], function(f) f[[3]])
  levels <- levels[!is.na(levels)]
  factor(dplyr::case_when(...), levels = levels)
}

```

<!-- ## Baseline diagram data -->
```{r baseline-diagram-data, eval = FALSE}
# #pull all people who completed baseline
# url <- "https://redcap.ucdenver.edu/api/"
# formData <- list("token"=.token,
#                  content='report',
#                  format='csv',
#                  report_id='98678',
#                  csvDelimiter='',
#                  rawOrLabel='label',
#                  rawOrLabelHeaders='raw',
#                  exportCheckboxLabel='false',
#                  returnFormat='json'
# )
# response <- httr::POST(url, body = formData, encode = "form")
# needs_diagram_baseline <- httr::content(response)
# 
# #create egor object using that data, the output is e2 from the function
# pna_qual <- wrangle_pna(needs_diagram_baseline,
#                             att_start = "altgender_a1",
#                             att_end = "altquitnow_a25",
#                             aa_start = "m1_2",
#                             a1 = "alter1",
#                             a25 = "alter25")
# 
# #what records are included in the report
# allrecords <- as.vector(as.numeric(pna_qual$ego$.egoID))
# 
# # CR 01/02/24
# # Commented here to get the same participant for diagram development
# records <- sort(sample(allrecords, 10))
# 
# # The records that camille used for development
# records <- c(1, 16, 18, 35, 36, 46, 56, 62, 94, 95)
```


```{r, pull data}
# pull all people who completed baseline
# Pulls data from report titled "ACTION: Needs Qualitative Diagrams"
# Report pulls anyone who has at least one empty diagram

# Set Redcap URL
url <- "https://redcap.ucdenver.edu/api/"

# Set formData, contains tokent and other parameters
# Set the report_id to pull from 
formData <- list("token"=.token,
                 content='report',
                 format='csv',
                 report_id='109108',
                 csvDelimiter='',
                 rawOrLabel='label',
                 rawOrLabelHeaders='raw',
                 exportCheckboxLabel='false',
                 returnFormat='json'
)

# Create response object using formData
response <- httr::POST(url, body = formData, encode = "form")

# Create needs_qual_diagram which is the main data frame for generating
# network diagrams
needs_qual_diagram <- httr::content(response)


# Create egor object 
# Uses the main data frame (needs_qual_diagram) and outputs e2 ego R object
pna_qual <- wrangle_pna(needs_qual_diagram,
                            att_start = "altgender_a1",
                            att_end = "altquitnow_a25",
                            aa_start = "m1_2",
                            a1 = "alter1",
                            a25 = "alter25")

# what records are included in the report
allrecords <- as.vector(as.numeric(pna_qual$ego$.egoID))

# CR 01/02/24
# Commented here to get the same participant for diagram development
# records <- sort(sample(allrecords, 10))

# The records that camille used for development
# records <- c(1, 16, 18, 35, 36, 46, 56, 62, 94, 95)

records <- allrecords

```


```{r, global settings}
# Set diagram parameters ----------------------------------------------------
# Set colors for smokers and non-smokers as vector
smoke_colors <- c("#92c5de", "#f4a582")

# Set shapes for gender as vector
shapes <- c("triangle", "circle", "square")
```

### Viz1 - Betweenness Centrality
```{r visualization1}
# Set records to the master allrecords list, vector will then be pared down
# eliminate those that end up with problems.
records <- allrecords

# Set scales
scaled <- seq(0.75,2,length = 5) 
scaled_1 <- seq(0.75, 3, length = 5)

for (i in records){

  # Prep diagram data ----------------------------------------------------------
  # Create a 25 by 21 subject specific tibble containing information
  # regarding the characteristics of the alters listed by the subject
  nodes <- pna_qual$alter %>% 
    filter(.egoID == i) %>% 
    select(-.egoID) %>% 
    rename(id = .altID)
  
  # Create an X by 4 tibble that is subject specific that contains
  # the weight as a 1 or 4; values of pna_qual$aatie$weight are
  # only Somewhat likely or Very likely. X represents the available
  # ties between alters that the subject provided
  links <- pna_qual$aatie %>% 
    filter(.egoID == i) %>% 
    select(-.egoID) %>%
    rename(from = .srcID, 
           to = .tgtID,
           type = "weight") %>% 
    mutate(weight = dplyr::case_when(type == "Somewhat likely" ~ 1,
                                     type == "Very likely" ~ 4))
  
  # Create an igraph object from links and vertices ----------------------------
  net <- graph_from_data_frame(d=links, vertices=nodes, directed=F) 
  graph <- as_tbl_graph(net)
  
  # Set diagram parameters ----------------------------------------------------
  # Set colors for smokers and non-smokers as vector
  smoke_colors <- c("#92c5de", "#f4a582")
  
  # Set smoking status the igraph object
  V(net)$smokingstatus <- ifelse(V(net)$alttobacco_a == "No", 1, 2)
  
  # Set the smoking color in the igraph object
  V(net)$color <- smoke_colors[V(net)$smokingstatus]
  
  # Set shapes for gender as vector
  shapes <- c("triangle", "circle", "square")
  
  # Set the gender values in the igraph object depending on values in altgender_a
  V(net)$gender <- ifelse(V(net)$altgender_a == "Man (including transman and transmasculine)", 1,
                          ifelse(V(net)$altgender_a == "Woman (including transwoman and transfeminine)", 2, 3))
  
  # Index the shapes vector using the gender numerical values
  V(net)$shape <- shapes[V(net)$gender]
  
  # Set line weight for the edges
  E(net)$width <- E(net)$weight

  # Node size based on betweenness values
  # Calculate betweenness centrality values
  between_cen <- betweenness(net)

  # Rescale the node sizes so they appear in a consistent size regardless of
  # underlying values and so that nodes are not overplotted
  V(net)$size <- scales::rescale(betweenness(net), to = c(5,15))

  
  # Fruchterman-Reingold layout - trying to expand a bit not sure if this is working
  l <- layout_with_fr(net)
  
  # Create a temporary png file ------------------------------------------------
  SimplePlot.file  <- here("03 Code/Network visualizations", str_c("visualization1_ID", i, ".png"))

  #create a temporary png file
  SimplePlot.file <- tempfile(pattern = paste0("qual_diagram1_ID", i, "_"),
                              fileext = ".png")
  
  png(filename = SimplePlot.file, width = 2200, height = 1400, res =100, units = "px",
      pointsize = 24)
  
  # expand margin on the right side for the legend
  par(mar=c(par("mar")[1:3], 10))
  
  # plot the diagram
  plot(net, 
       vertex.size = V(net)$size, 
       layout = l*1, # original value was .25 
       vertex.label = V(net)$aname, 
       vertex.label.degree = pi/2, 
       vertex.label.dist = 0,
       ylim = c(-1, 1),
       xlim = c(-1, 1), 
       asp = 0)

  # Create and plot sub legends ------------------------------------------------
  # Legend 1 - Smoker vs Non-smoker
  l1 <- legend("topleft",
               legend = c("Smoker", "Non-smoker"),
               pch = 19, bty = "n",
               pt.cex = scaled[3],
               col = c("#f4a582", "#92c5de"),
               title = "Smoking status",
               xpd=TRUE, inset=c(1,0), title.adj=c(0))
  
  # Legend 2 - Gender shape
  # add second legend and adjust x axis position based on height of first legend
  l2 <- legend(x = l1$rect$left, y = l1$rect$top - l1$rect$h,
               legend = c("Man", "Woman", "Different gender\nor declined"),
               pch = c(17, 19, 15), bty = "n",
               pt.cex = scaled[3], title.adj=c(0),
               title = "Gender", xpd = TRUE,
               inset = c(1,0))
  
  # Legend 3 - Betweenness measure
  # add third legend and adjust x axis position based on height of second legend
  # col is the line color of the scale
  # pt.bg is the fill color
  legend(x = l2$rect$left, y = l2$rect$top - l2$rect$h,
         
         # Set the character labels for the scale of betweenness
         # legend=c(round(min(between_cen)), "",
         #          "", "", round(max(between_cen))),
         
         # Remove the character labels from the betweenness legend
         legend=c("", "","", "", ""),
         
         # Set the size of the betweenness circle indicators
         pt.cex= scaled_1,
         
         # Additional legend characteristics
         col='black', pch=21, pt.bg='black', bty = "n",
         title = "Betweenness", xpd = TRUE,
         inset = c(1,0), title.adj=c(0))
  
  dev.off()
  
  #upload to REDCap
  REDCapR::redcap_upload_file_oneshot(file_name = SimplePlot.file,
                                      record = i,
                                      field = "qual_diagram_1",
                                      redcap_uri = url,
                                      token = .token)
  unlink(SimplePlot.file)
}
```

### Viz2 - Degree Centrality
```{r visualization2}
# Degree centrality

# Set records to the master allrecords list, vector will then be pared down
# eliminate those that end up with problems.
records <- allrecords

# Set the scaled3 values
scaled3 <- seq(0.75, 3, length = 5)

for(i in records){
  # i <- records[3]
  #select data for nodes and links
  nodes <- pna_qual$alter %>% 
    filter(.egoID == i) %>% 
    select(-.egoID) %>% 
    rename(id = .altID)
  
  links <- pna_qual$aatie %>% 
    filter(.egoID == i) %>% 
    select(-.egoID) %>%
    rename(from = .srcID, to = .tgtID,
           type = "weight") %>% 
    mutate(weight = dplyr::case_when(type == "Somewhat likely" ~ 1,
                                     type == "Very likely" ~ 4))
  
  #turn into an igraph object
  net <- graph_from_data_frame(d=links, vertices=nodes, directed=F) 
  graph <- as_tbl_graph(net)
  
  #set smoking colors 
  smoke_colors <- c("#92c5de", "#f4a582")
  V(net)$smokingstatus <- ifelse(V(net)$alttobacco_a == "No", 1, 2)
  V(net)$color <- smoke_colors[V(net)$smokingstatus]
  
  #weight for edges
  # E(net)$width <- E(net)$weight
  
  result <- try(E(net)$width <- E(net)$weight)
  
  if(grepl("Error", result[1])){
    print(i) 
    }
  else{

    #degree centrality will be used for the size - rescaling to be between 1-10
    degree_cen <- igraph::degree(net)
    V(net)$size <- scales::rescale(igraph::degree(net), to = c(5,15))
    
    #shapes for gender
    shapes <- c("triangle", "circle", "square")
    V(net)$gender <- ifelse(V(net)$altgender_a == "Man (including transman and transmasculine)", 1,
                            ifelse(V(net)$altgender_a == "Woman (including transwoman and transfeminine)", 2, 3))
    V(net)$shape <- shapes[V(net)$gender]
    
    # Fruchterman-Reingold layout - trying to expand a bit not sure if this is working
    l <- layout_with_fr(net)
   
     #create a temporary png file
    # SimplePlot.file <- paste0("C:/Users/hochheic/OneDrive - The University of Colorado Denver/Helpers-Stay-Quit/03 Code/Network visualizations/visualization2_ID", i, ".png")
    SimplePlot.file  <- here("03 Code/Network visualizations", str_c("visualization2_ID", i, ".png"))
    
        #create a temporary png file
  SimplePlot.file <- tempfile(pattern = paste0("qual_diagram2_ID", i, "_"),
                              fileext = ".png")
  
    png(filename = SimplePlot.file, width = 2200, height = 1400, res =100, units = "px",
        pointsize = 24)
    # expand margin on the right side for the legend
    par(mar=c(par("mar")[1:3], 10))
    # plot
    plot(net, 
         layout = l*0.25, 
         vertex.label = V(net)$aname,
         ylim = c(-1, 1), 
         xlim = c(-1, 1), 
         asp = 0)
    
    # add the first legend and save it's position
    l1 <- legend("topleft",
                 legend = c("Smoker", "Non-smoker"),
                 pch = 19, bty = "n",
                 pt.cex = scaled[3],
                 col = c("#f4a582", "#92c5de"),
                 title = "Smoking status",
                 xpd=TRUE, inset=c(1,0), title.adj=c(0))
    
    # add second legend and adjust x axis position based on height of first legend
    l2 <- legend(x = l1$rect$left, y = l1$rect$top - l1$rect$h,
                 legend = c("Man", "Woman", "Different gender\nor declined"),
                 pch = c(17, 19, 15), bty = "n",
                 pt.cex = scaled[3], title.adj=c(0),
                 title = "Gender", xpd = TRUE,
                 inset = c(1,0))
    # add third legend and adjust x axis position based on height of second legend
    legend(x = l2$rect$left, y = l2$rect$top - l2$rect$h,
  
           # legend=c(min(degree_cen), "",
           #          "", "", max(degree_cen)),
           # Remove the character labels from the betweenness legend
           legend=c("", "","", "", ""),
           
           pt.cex= scaled3,
           col='black',
           pch=21, 
           pt.bg='black', 
           bty = "n", # CR 12/11/2023 changed scaled3 to scaled[3]
           title = "Degree Centrality", xpd = TRUE,
           inset = c(1,0), title.adj=c(0))
    
    dev.off()
    
    #upload to REDCap
    REDCapR::redcap_upload_file_oneshot(file_name = SimplePlot.file,
                                        record = i,
                                        field = "qual_diagram_2",
                                        redcap_uri = url,
                                        token = .token)
    unlink(SimplePlot.file)     
    
    
    
      }
}

```

### Viz3 - Closeness Centrality
```{r visualization3}
# Closeness
#this is the same one we send through REDCap

# Set records to the master allrecords list, vector will then be pared down
# eliminate those that end up with problems.
records <- allrecords

# Set scaled 3 values
# *** Should not be needed since it's setup in viz1 section
# scaled3 <- seq(0.75, 3, length = 5)

# Set the scale so that it mimics viz1 and viz2
scaled4 <- seq(1, 4, length = 5)

for(i in records){
  # i <- records[3]
  #select data for nodes and links
  nodes <- pna_qual$alter %>% 
    filter(.egoID == i) %>% 
    select(-.egoID) %>% 
    rename(id = .altID)
  
  links <- pna_qual$aatie %>% 
    filter(.egoID == i) %>% 
    select(-.egoID) %>%
    rename(from = .srcID, to = .tgtID,
           type = "weight") %>% 
    mutate(weight = dplyr::case_when(type == "Somewhat likely" ~ 1,
                                     type == "Very likely" ~ 4))
  
  #turn into an igraph object
  net <- graph_from_data_frame(d=links, vertices=nodes, directed=F) 
  graph <- as_tbl_graph(net)
  
  #set smoking colors 
  smoke_colors <- c("#92c5de", "#f4a582")
  V(net)$smokingstatus <- ifelse(V(net)$alttobacco_a == "No", 1, 2)
  V(net)$color <- smoke_colors[V(net)$smokingstatus]
  
  #weight for edges
  # E(net)$width <- E(net)$weight
  
  result <- try(E(net)$width <- E(net)$weight)
  
  if(grepl("Error", result[1])){
    print(i) 
    }
  else{
  
    #betweenness will be used for the size - rescaling to be between 1-10
    #size for closeness
    V(net)$size <-ifelse(V(net)$altclose_a == "Not close at all", scaled4[1],
                                          ifelse(V(net)$altclose_a == "A little close", scaled4[2],
                                                 ifelse(V(net)$altclose_a == "Somewhat close", scaled4[3],
                                                        ifelse(V(net)$altclose_a == "Quite close", scaled4[4],
                                                               scaled4[5]))))*3
    #shapes for gender
    shapes <- c("triangle", "circle", "square")
    V(net)$gender <- ifelse(V(net)$altgender_a == "Man (including transman and transmasculine)", 1,
                            ifelse(V(net)$altgender_a == "Woman (including transwoman and transfeminine)", 2, 3))
    V(net)$shape <- shapes[V(net)$gender]
    # Fruchterman-Reingold layout - trying to expand a bit not sure if this is working
    l <- layout_with_fr(net)
    #create a temporary png file
    # SimplePlot.file <- paste0("C:/Users/hochheic/OneDrive - The University of Colorado Denver/Helpers-Stay-Quit/03 Code/Network visualizations/visualization3_ID", i, ".png")
    SimplePlot.file  <- here("03 Code/Network visualizations", str_c("visualization3_ID", i, ".png"))
    
        #create a temporary png file
  SimplePlot.file <- tempfile(pattern = paste0("qual_diagram3_ID", i, "_"),
                              fileext = ".png")
  
    png(filename = SimplePlot.file, width = 2200, height = 1400, res =100, units = "px",
        pointsize = 24)
    # expand margin on the right side for the legend
    par(mar=c(par("mar")[1:3], 10))
    # plot
    plot(net, layout = l*0.25, vertex.label = V(net)$aname,
         ylim = c(-1, 1), xlim = c(-1, 1), asp = 0)
    # add the first legend and save it's position
    l1 <- legend("topleft",
                 legend = c("Smoker", "Non-smoker"),
                 pch = 19, bty = "n",
                 pt.cex = scaled[3],
                 col = c("#f4a582", "#92c5de"),
                 title = "Smoking status",
                 xpd=TRUE, inset=c(1,0), title.adj=c(0))
    
    # add second legend and adjust x axis position based on height of first legend
    l2 <- legend(x = l1$rect$left, y = l1$rect$top - l1$rect$h,
                 legend = c("Man", "Woman", "Different gender\nor declined"),
                 pch = c(17, 19, 15), bty = "n",
                 pt.cex = scaled[3], title.adj=c(0),
                 title = "Gender", xpd = TRUE,
                 inset = c(1,0))
    # add third legend and adjust x axis position based on height of second legend
    legend(x = l2$rect$left, y = l2$rect$top - l2$rect$h,
           legend=c("Not close at all", "A little close",
                    "Somewhat close", "Quite close", "Very close"),
           pt.cex= scaled3,col='black',pch=21, pt.bg='black', bty = "n",
           title = "How close to you", xpd = TRUE,
           inset = c(1,0), title.adj=c(0))
    
    dev.off()
  
    #upload to REDCap
    REDCapR::redcap_upload_file_oneshot(file_name = SimplePlot.file,
                                        record = i,
                                        field = "qual_diagram_3",
                                        redcap_uri = url,
                                        token = .token)
    unlink(SimplePlot.file)
    
    }
}

```

### Viz4 - Frequency of interaction
```{r visualization4}
# Frequency of interaction

# Set records to the master allrecords list, vector will then be pared down
# eliminate those that end up with problems.
records <- allrecords

# Set the scale so that it mimics viz1 and viz2
# scaled4 <- seq(0.75, 3, length = 5)
scaled4 <- seq(2, 7, length = 5)

for(i in records){
  # i <- records[3]
  #select data for nodes and links
  nodes <- pna_qual$alter %>% 
    filter(.egoID == i) %>% 
    select(-.egoID) %>% 
    rename(id = .altID)
  
  links <- pna_qual$aatie %>% 
    filter(.egoID == i) %>% 
    select(-.egoID) %>%
    rename(from = .srcID, to = .tgtID,
           type = "weight") %>% 
    mutate(weight = dplyr::case_when(type == "Somewhat likely" ~ 1,
                                     type == "Very likely" ~ 4))
  
  #turn into an igraph object
  net <- graph_from_data_frame(d=links, vertices=nodes, directed=F) 
  graph <- as_tbl_graph(net)
  
  #set smoking colors 
  smoke_colors <- c("#92c5de", "#f4a582")
  V(net)$smokingstatus <- ifelse(V(net)$alttobacco_a == "No", 1, 2)
  V(net)$color <- smoke_colors[V(net)$smokingstatus]
  
  #weight for edges
  # E(net)$width <- E(net)$weight
  
  result <- try(E(net)$width <- E(net)$weight)
  
  if(grepl("Error", result[1])){
    print(i) 
    } else {
    
    #betweenness will be used for the size - rescaling to be between 1-10
    #size for frequency of interaction
    V(net)$size <- ifelse(V(net)$altintfreq_a == "Once a year or so", scaled4[1],
                                          ifelse(V(net)$altintfreq_a == "At least once every several months", scaled4[2],
                                                 ifelse(V(net)$altintfreq_a == "At least once a month", scaled4[3],
                                                        ifelse(V(net)$altintfreq_a == "At least once a week", scaled4[4],
                                                               scaled4[5]))))*2
    #shapes for gender
    shapes <- c("triangle", "circle", "square")
    V(net)$gender <- ifelse(V(net)$altgender_a == "Man (including transman and transmasculine)", 1,
                            ifelse(V(net)$altgender_a == "Woman (including transwoman and transfeminine)", 2, 3))
    V(net)$shape <- shapes[V(net)$gender]
    # Fruchterman-Reingold layout - trying to expand a bit not sure if this is working
    l <- layout_with_fr(net)
    #create a temporary png file
    # SimplePlot.file <- paste0("C:/Users/hochheic/OneDrive - The University of Colorado Denver/Helpers-Stay-Quit/03 Code/Network visualizations/visualization4_ID", i, ".png")
    SimplePlot.file  <- here("03 Code/Network visualizations", str_c("visualization4_ID", i, ".png"))
    
        #create a temporary png file
  SimplePlot.file <- tempfile(pattern = paste0("qual_diagram4_ID", i, "_"),
                              fileext = ".png")
  
    png(filename = SimplePlot.file, width = 2200, height = 1400, res =100, units = "px",
        pointsize = 24)
    # expand margin on the right side for the legend
    par(mar=c(par("mar")[1:3], 10))
    # plot
    plot(net, layout = l*0.25, vertex.label = V(net)$aname,
         ylim = c(-1, 1), xlim = c(-1, 1), asp = 0)
    # add the first legend and save it's position
    l1 <- legend("topleft",
                 legend = c("Smoker", "Non-smoker"),
                 pch = 19, bty = "n",
                 pt.cex = scaled[3],
                 col = c("#f4a582", "#92c5de"),
                 title = "Smoking status",
                 xpd=TRUE, inset=c(1,0), title.adj=c(0))
    
    # add second legend and adjust x axis position based on height of first legend
    l2 <- legend(x = l1$rect$left, y = l1$rect$top - l1$rect$h,
                 legend = c("Man", "Woman", "Different gender\nor declined"),
                 pch = c(17, 19, 15), bty = "n",
                 pt.cex = scaled[3], title.adj=c(0),
                 title = "Gender", xpd = TRUE,
                 inset = c(1,0))
    # add third legend and adjust x axis position based on height of second legend
    legend(x = l2$rect$left, y = l2$rect$top - l2$rect$h,
           legend=c("Once a year or so", "At least once every\nseveral months",
                    "At least once a month", "At least once a week", "Almost every day"),
           pt.cex= scaled3,col='black',pch=21, pt.bg='black', bty = "n",
           title = "How frequently you interact", xpd = TRUE,
           inset = c(1,0), title.adj=c(0))
    
    dev.off()
    
    #upload to REDCap
    REDCapR::redcap_upload_file_oneshot(file_name = SimplePlot.file,
                                        record = i,
                                        field = "qual_diagram_4",
                                        redcap_uri = url,
                                        token = .token)
    unlink(SimplePlot.file)     
    
    
    
      }
}

```

### Viz5 - Age
```{r visualization5}
# Age

# Set records to the master allrecords list, vector will then be pared down
# eliminate those that end up with problems.
records <- allrecords

# scaled5 <- c(0.5, 0.75, 1, 2, 3)
scaled5 <- seq(2, 7, length = 5)

for(i in records){
  # i <- records[1]
  #select data for nodes and links
  nodes <- pna_qual$alter %>% 
    filter(.egoID == i) %>% 
    select(-.egoID) %>% 
    rename(id = .altID)
  
  links <- pna_qual$aatie %>% 
    filter(.egoID == i) %>% 
    select(-.egoID) %>%
    rename(from = .srcID, to = .tgtID,
           type = "weight") %>% 
    mutate(weight = dplyr::case_when(type == "Somewhat likely" ~ 1,
                                     type == "Very likely" ~ 4))
  
  #turn into an igraph object
  net <- graph_from_data_frame(d=links, vertices=nodes, directed=F) 
  graph <- as_tbl_graph(net)
  
  #set smoking colors 
  smoke_colors <- c("#92c5de", "#f4a582")
  V(net)$smokingstatus <- ifelse(V(net)$alttobacco_a == "No", 1, 2)
  V(net)$color <- smoke_colors[V(net)$smokingstatus]
  
  #weight for edges
  # E(net)$width <- E(net)$weight
  
  result <- try(E(net)$width <- E(net)$weight)
  
  if(grepl("Error", result[1])){
    print(i) 
    } else {
      
    #betweenness will be used for the size - rescaling to be between 1-10
    #size for age
    V(net)$size <- ifelse(V(net)$altage_a == "Don't know", scaled5[1],
                                          ifelse(V(net)$altage_a == "12 or Under", scaled5[2],
                                                 ifelse(V(net)$altage_a == "13 - 17", scaled5[3],
                                                        ifelse(V(net)$altage_a == "18 - 64", scaled5[4],
                                                               scaled5[5]))))*2
    #shapes for gender
    shapes <- c("triangle", "circle", "square")
    V(net)$gender <- ifelse(V(net)$altgender_a == "Man (including transman and transmasculine)", 1,
                            ifelse(V(net)$altgender_a == "Woman (including transwoman and transfeminine)", 2, 3))
    V(net)$shape <- shapes[V(net)$gender]
    
    # Fruchterman-Reingold layout - trying to expand a bit not sure if this is working
    l <- layout_with_fr(net)
    
    #create a temporary png file
    # SimplePlot.file <- paste0("C:/Users/hochheic/OneDrive - The University of Colorado Denver/Helpers-Stay-Quit/03 Code/Network visualizations/visualization5_ID", i, ".png")
    SimplePlot.file  <- here("03 Code/Network visualizations", str_c("visualization5_ID", i, ".png"))
    
        #create a temporary png file
  SimplePlot.file <- tempfile(pattern = paste0("qual_diagram5_ID", i, "_"),
                              fileext = ".png")
  
    png(filename = SimplePlot.file, width = 2200, height = 1400, res =100, units = "px",
        pointsize = 24)
    # expand margin on the right side for the legend
    par(mar=c(par("mar")[1:3], 10))
    # plot
    plot(net, layout = l*0.25, vertex.label = V(net)$aname,
         ylim = c(-1, 1), xlim = c(-1, 1), asp = 0)
    # add the first legend and save it's position
    l1 <- legend("topleft",
                 legend = c("Smoker", "Non-smoker"),
                 pch = 19, bty = "n",
                 pt.cex = scaled[3],
                 col = c("#f4a582", "#92c5de"),
                 title = "Smoking status",
                 xpd=TRUE, inset=c(1,0), title.adj=c(0))
    
    # add second legend and adjust x axis position based on height of first legend
    l2 <- legend(x = l1$rect$left, y = l1$rect$top - l1$rect$h,
                 legend = c("Man", "Woman", "Different gender\nor declined"),
                 pch = c(17, 19, 15), bty = "n",
                 pt.cex = scaled[3], title.adj=c(0),
                 title = "Gender", xpd = TRUE,
                 inset = c(1,0))
    # add third legend and adjust x axis position based on height of second legend
    legend(x = l2$rect$left, y = l2$rect$top - l2$rect$h,
           legend=c("Don't know", "12 or Under",
                    "13 - 17", "18 - 64", "65 or older"),
           pt.cex= scaled3,col='black',pch=21, pt.bg='black', bty = "n",
           title = "Age", xpd = TRUE,
           inset = c(1,0), title.adj=c(0))
    
    dev.off()
  
    #upload to REDCap
    REDCapR::redcap_upload_file_oneshot(file_name = SimplePlot.file,
                                        record = i,
                                        field = "qual_diagram_5",
                                        redcap_uri = url,
                                        token = .token)
    unlink(SimplePlot.file)     

      }
}

```
