---
title: "5 Network Diagram Development"
author: "Camille Hochheimer, PhD"
date: "`r Sys.Date()`"
output: html_document
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(egor) #for diagrams
library(here) #for sharing this RProject
library(tidyverse) #for data wrangling
library(purrr) 
library(network) #for diagrams
library(ggplot2) #for diagrams
library(igraph) #for diagrams

library(ggraph)
library(tidygraph)

#your API token
.token <- Sys.getenv("HSQ_api")

#these are for controlling the size of the circles for the network diagrams
scaled <- seq(0.75,2,length = 5) 

#function for wrangling PNA data
wrangle_pna <- function(pna, att_start, att_end, aa_start,
                        a1, a25,
                        namerange = 2:26, tierange = 502:801){
  
  # pna <- needs_diagram_baseline
  # namerange <- 2:26
  # tierange <- 502:801
  # att_start <- "altgender_a1"
  # att_end <- "altquitnow_a25"
  # aa_start <- "m1_2"
  # a1 <- "alter1"
  # a25 <- "alter25"
  
  pna2 <- pna %>% 
    rowwise() %>% 
    #get rid of people who didn't name an alter or any alter-alter ties
    dplyr::select(-starts_with("network_diagram_")) %>% 
    dplyr::filter(sum(is.na(across(all_of(namerange)))) == 0 &
                    sum(is.na(across(all_of(tierange))), na.rm = TRUE) == 0) %>%
    mutate(across(.cols = c(starts_with("alttobacco_a"), starts_with("altsmoke_a")),
                  ~case_when(.x == "Checked" ~ "Yes",
                             .x == "Unchecked" ~ "No")))
  # mutate_all(funs(str_replace(., "Checked", "Yes"))) %>% 
  # mutate_all(funs(str_replace(., "Unchecked", "No")))
  
  
  et <- onefile_to_egor(egos = pna2,
                        ID.vars = list(ego = "record_id"),
                        # Name of Variable with the first alter attribute
                        attr.start.col = att_start,
                        # Name of variable with last alter attribute
                        attr.end.col = att_end, 
                        # Number of maximum alters that were named by participants
                        max.alters = 25, 
                        # Name of first alter-alter variable
                        aa.first.var = aa_start) 
  
  alter_filter2 <- 
    et %>% 
    as_tibble() %>% 
    arrange(.egoID) %>% 
    select(eval(substitute(a1)):eval(substitute(a25))) %>% 
    mutate(across(.fns = ~ !is.na(.))) %>% 
    as.data.frame() %>% 
    tidyr::pivot_longer(cols = everything()) %>% 
    pull(value)
  
  e2 <- 
    et %>% 
    activate(alter) %>% 
    filter(alter_filter2) %>% 
    activate(aatie) %>% 
    filter(weight != "")
  
  #add alter names to the alter data
  e2$alter$aname <- c(t(e2$ego[,2:26]))
  
  # e2$aatie$weight2 <- ifelse(e2$aatie$weight == "Not at all likely", 0.01, #set to zero
  #                            ifelse(e2$aatie$weight == "Somewhat likely", 1, 2))
  e2$aatie <- e2$aatie %>% 
    #show somewhat likely and very likely
    filter(weight != "Not at all likely")
  # e2$aatie$weight2 <- ifelse(e2$aatie$weight == "Somewhat likely", 1, 2)
  #show just very likel
  #   filter(weight == "Very likely")
  # e2$aatie$weight2 <- 3
  
  return(e2)
}

# triangle vertex shape
mytriangle <- function(coords, v=NULL, params) {
  vertex.color <- params("vertex", "color")
  if (length(vertex.color) != 1 && !is.null(v)) {
    vertex.color <- vertex.color[v]
  }
  vertex.size <- 1/200 * params("vertex", "size")
  if (length(vertex.size) != 1 && !is.null(v)) {
    vertex.size <- vertex.size[v]
  }
  
  symbols(x=coords[,1], y=coords[,2], bg=vertex.color,
          stars=cbind(vertex.size, vertex.size, vertex.size),
          add=TRUE, inches=FALSE)
}

# clips as a circle
add_shape("triangle", clip=shapes("circle")$clip,
          plot=mytriangle)

#factor with case_when
fct_case_when <- function (...){
  args <- as.list(match.call())
  levels <- sapply(args[-1], function(f) f[[3]])
  levels <- levels[!is.na(levels)]
  factor(dplyr::case_when(...), levels = levels)
}

```



## Baseline diagram data
```{r baseline-diagram-data}
#pull all people who completed baseline
url <- "https://redcap.ucdenver.edu/api/"
formData <- list("token"=.token,
                 content='report',
                 format='csv',
                 report_id='98678',
                 csvDelimiter='',
                 rawOrLabel='label',
                 rawOrLabelHeaders='raw',
                 exportCheckboxLabel='false',
                 returnFormat='json'
)
response <- httr::POST(url, body = formData, encode = "form")
needs_diagram_baseline <- httr::content(response)

#create egor object using that data, the output is e2 from the function
pna_baseline <- wrangle_pna(needs_diagram_baseline,
                            att_start = "altgender_a1",
                            att_end = "altquitnow_a25",
                            aa_start = "m1_2",
                            a1 = "alter1",
                            a25 = "alter25")

#what records are included in the report
allrecords <- as.vector(as.numeric(pna_baseline$ego$.egoID))

# CR 01/02/24
# Commented here to get the same participant for diagram development
records <- sort(sample(allrecords, 10))

# The records that camille used for development
records <- c(1, 16, 18, 35, 36, 46, 56, 62, 94, 95)
```

### Baseline Diagram base r
```{r baseline-diagram-base-r}
# 
# # uses igraph
# for(i in records){
#   # i <- records[3]
#   #select data for nodes and links
#   nodes <- pna_baseline$alter %>% 
#     filter(.egoID == i) %>% 
#     select(-.egoID) %>% 
#     rename(id = .altID)
#   
#   links <- pna_baseline$aatie %>% 
#     filter(.egoID == i) %>% 
#     select(-.egoID) %>%
#     rename(from = .srcID, to = .tgtID,
#            type = "weight") %>% 
#     mutate(weight = dplyr::case_when(type == "Somewhat likely" ~ 1,
#                                      type == "Very likely" ~ 4))
#   
#   #turn into an igraph object
#   net <- graph_from_data_frame(d=links, vertices=nodes, directed=F) 
#   graph <- tidygraph::as_tbl_graph(net)
#   #set smoking colors 
#   smoke_colors <- c("#92c5de", "#f4a582")
#   V(net)$smokingstatus <- ifelse(V(net)$alttobacco_a == "No", 1, 2)
#   V(net)$color <- smoke_colors[V(net)$smokingstatus]
#   #weight for edges
#   E(net)$width <- E(net)$weight
#   #size for closeness
#   V(net)$size <- scales::rescale(ifelse(V(net)$altclose_a == "Not close at all", scaled[1],
#                                         ifelse(V(net)$altclose_a == "A little close", scaled[2],
#                                                ifelse(V(net)$altclose_a == "Somewhat close", scaled[3],
#                                                       ifelse(V(net)$altclose_a == "Quite close", scaled[4],
#                                                              scaled[5])))), to = c(1,10))
#   #shapes for gender
#   shapes <- c("triangle", "circle", "square")
#   V(net)$gender <- ifelse(V(net)$altgender_a == "Man (including transman and transmasculine)", 1,
#                           ifelse(V(net)$altgender_a == "Woman (including transwoman and transfeminine)", 2, 3))
#   V(net)$shape <- shapes[V(net)$gender]
#   # Fruchterman-Reingold layout - trying to expand a bit not sure if this is working
#   l <- layout_with_fr(net)
#   #create a temporary png file
#   # SimplePlot.file <- paste0("C:/Users/hochheic/OneDrive - The University of Colorado Denver/Helpers-Stay-Quit/03 Code/Network visualizations/networkdiagram_ID", i, "_baser.png")
#   # CR 12/11/2023 - Path to simplePlot file changed to locl directory.
#   SimplePlot.file  <- here("03 Code/Network visualizations", str_c("networkdiagram_ID", i, "_baser.png"))
#   png(filename = SimplePlot.file, width = 2200, height = 1400, res =100, units = "px",
#       pointsize = 24)
#   # expand margin on the right side for the legend
#   par(mar=c(par("mar")[1:3], 10))
#   # plot
#   plot(net, layout = l*0.25, vertex.label = V(net)$aname,
#        ylim = c(-1, 1), xlim = c(-1, 1), asp = 0)
#   # add the first legend and save it's position
#   l1 <- legend("topleft",
#                legend = c("Smoker", "Non-smoker"),
#                pch = 19, bty = "n",
#                pt.cex = scaled[3],
#                col = c("#f4a582", "#92c5de"),
#                title = "Smoking status",
#                xpd=TRUE, inset=c(1,0), title.adj=c(0))
#   
#   # add second legend and adjust x axis position based on height of first legend
#   l2 <- legend(x = l1$rect$left, y = l1$rect$top - l1$rect$h,
#                legend = c("Man", "Woman", "Different gender\nor declined"),
#                pch = c(17, 19, 15), bty = "n",
#                pt.cex = scaled[3], title.adj=c(0),
#                title = "Gender", xpd = TRUE,
#                inset = c(1,0))
#   # add third legend and adjust x axis position based on height of second legend
#   legend(x = l2$rect$left, y = l2$rect$top - l2$rect$h,
#          legend=c("Not close at all", "A little close",
#                   "Somewhat close", "Quite close", "Very close"),
#          pt.cex= scaled,col='black',pch=21, pt.bg='black', bty = "n",
#          title = "How close to you", xpd = TRUE,
#          inset = c(1,0), title.adj=c(0))
#   
#   dev.off()
# }
```

### Baseline diagram ggraph
```{r baseline-diagram-ggraph}
# # CR 12/11/2023 - 
# # Produces a plot, that overwrites the file above, thicker lines, gray bg instead of white
# # no nodes displayed.
# # Scale of how close is different because not close at all is thicker than a little close
# 
# for(i in records){
#   # i <- records[3]
#   #select data for nodes and links
#   nodes <- pna_baseline$alter %>% 
#     filter(.egoID == i) %>% 
#     select(-.egoID) %>% 
#     rename(id = .altID) %>% 
# ########## Why does this not want to keep the factor order????
#     mutate(gender = factor(dplyr::case_when(altgender_a == 
#                                               "Man (including transman and transmasculine)" ~ 1,
#                                             altgender_a == 
#                                               "Woman (including transwoman and transfeminine)" ~ 2,
#                                             TRUE ~ 3),
#                            levels = c("Man", "Woman", "Different gender or declined")))
#   # mutate(gender = fct_case_when(altgender_a == 
#   #                                 "Man (including transman and transmasculine)" ~ "Man",
#   #                               altgender_a == 
#   #                                 "Woman (including transwoman and transfeminine)" ~ "Woman",
#   #                               TRUE ~ "Different gender or declined"))
#   
#   links <- pna_baseline$aatie %>% 
#     filter(.egoID == i) %>% 
#     select(-.egoID) %>%
#     rename(from = .srcID, to = .tgtID,
#            type = "weight") %>% 
#     mutate(weight = dplyr::case_when(type == "Somewhat likely" ~ 1,
#                                      type == "Very likely" ~ 4))
#   
#   #turn into an igraph object
#   net <- graph_from_data_frame(d=links, vertices=nodes, directed=F) 
#   graph <- as_tbl_graph(net)
#   #create a temporary png file
#   # SimplePlot.file <- paste0("C:/Users/hochheic/OneDrive - The University of Colorado Denver/Helpers-Stay-Quit/03 Code/Network visualizations/networkdiagram_ID", i, "_ggraph.png")
#   SimplePlot.file  <- here("03 Code/Network visualizations", str_c("networkdiagram_ID", i, "_ggraph.png"))
# 
#   graph %>%  ggraph(layout = "fr") +
#     geom_edge_link(aes(width = weight)) +
#     geom_node_point(aes(color = alttobacco_a,
#                         size = altclose_a,
#                         shape = as.factor(gender))) +
#     geom_node_label(aes(label = aname), repel = TRUE) +
#     scale_colour_manual(values = c("#92c5de", "#f4a582"), 
#                         labels = c("Non-smoker", "Smoker")) +
#     scale_shape_manual(values = c("triangle", "circle", "square")) +
#     scale_edge_width(range = c(1,2), guide = "none") +
#     labs(color = "Smoking status",
#          size = "How close to you",
#          shape = "Gender") 
#   ggsave(filename = SimplePlot.file,
#          width = 2200, height = 1400, units = "px",
#          dpi = 300)
# }

```

### Testing ggraph
```{r testing-ggraph}
# # CR 12/11/2023 -
# # This version adds the vertices, takes out the scale for the thickness of the line
# 
# # i <- records[5] #CR 12/11/2023 - commented to utilized the i variable in the workspace
# #select data for nodes and links
# nodes <- pna_baseline$alter %>% 
#   filter(.egoID == i) %>% 
#   select(-.egoID) %>% 
#   rename(id = .altID) %>% 
#   mutate(gender = factor(dplyr::case_when(altgender_a == 
#                                             "Man (including transman and transmasculine)" ~ "Man",
#                                           altgender_a == 
#                                             "Woman (including transwoman and transfeminine)" ~ "Woman",
#                                           TRUE ~ "Different gender or declined"),
#                          levels = c("Man", "Woman", "Different gender or declined")))
# 
# links <- pna_baseline$aatie %>% 
#   filter(.egoID == i) %>% 
#   select(-.egoID) %>%
#   rename(from = .srcID, to = .tgtID,
#          type = "weight") %>% 
#   mutate(weight = dplyr::case_when(type == "Somewhat likely" ~ 1,
#                                    type == "Very likely" ~ 4))
# 
# #turn into an igraph object
# net <- graph_from_data_frame(d=links, vertices=nodes, directed=F) 
# betweenness(net)
# 
# ## trying ggraph
# graph <- as_tbl_graph(net)
# # graph %>% activate(edges)
# graph %>%  ggraph(layout = "fr") +
#   geom_edge_link(aes(width = weight)) +
#   geom_node_point(aes(color = alttobacco_a,
#                       linewidth = altclose_a,
#                       shape = factor(gender))) +
#   geom_node_label(aes(label = aname), repel = TRUE,
#                   label.fill = NULL) +
#   scale_colour_manual(values = c("#92c5de", "#f4a582"), 
#                       labels = c("Non-smoker", "Smoker")) +
#   scale_shape_manual(values = c("triangle", "circle", "square")) +
#   scale_edge_width(range = c(1,2), guide = "none") +
#   labs(color = "Smoking status",
#        size = "How close to you",
#        shape = "Gender") 

```

### Viz1 
```{r visualization1}
# Betweenness
# CR 12/11/2023 -
# Changed scaled3 to scaled[3], otherwise it errors out
# There is an environmental variable named scaled3 that is created downstream
# ***unsure if the right value is scaled3 or scaled[3]
# possibly scaled3 is needed from when its declared downstream, otherwise
# the strength of the connections is not displayed
# *** Needed for Viz2 too
# Scaled3 variable from downstream is as follows:

# Betweeness is a property of a node.So each node, should have a betweeness
# measure
# The number of nodes plotted should be the number of betweenness measures

## do we want an overall scale for betweenness?

# Set the scaled3 values
scaled3 <- seq(0.75, 3, length = 5)

# Uses igraph package
for(i in records){
  # i <- records[3]
  #select data for nodes and links
  # Number of nodes/alters should be 25
  nodes <- pna_baseline$alter %>% 
    filter(.egoID == i) %>% 
    select(-.egoID) %>% 
    rename(id = .altID)
  
  # links are on a range of 1 to 4
  links <- pna_baseline$aatie %>% 
    filter(.egoID == i) %>% 
    select(-.egoID) %>%
    rename(from = .srcID, to = .tgtID,
           type = "weight") %>% 
    mutate(weight = dplyr::case_when(type == "Somewhat likely" ~ 1,
                                     type == "Very likely" ~ 4))
  
  #turn into an igraph object
  net <- graph_from_data_frame(d=links, vertices=nodes, directed=F) 
  graph <- as_tbl_graph(net)
  
  #set smoking colors 
  smoke_colors <- c("#92c5de", "#f4a582")
  
  # Set smoking status and color
  V(net)$smokingstatus <- ifelse(V(net)$alttobacco_a == "No", 1, 2)
  V(net)$color <- smoke_colors[V(net)$smokingstatus]
  
  # line weight for edges
  E(net)$width <- E(net)$weight
  # E(net)$width <- scales::rescale(E(net)$weight, to = c(1, 10))
  
  #betweenness will be used for the size - rescaling to be between 1-10
  between_cen <- betweenness(net)
  
  # Commented out the scaling to see that would happen
  # 1-10 results in small node sizes
  #between_cen <- scales::rescale(betweenness(net), to = c(.75,3))
  
  # Commented out the scaling to see what it does to the node size.
  V(net)$size <- scales::rescale(betweenness(net), to = c(5,15))

  # CR scaling isn't necessary and produces ok, results, but will not be 
  # comparable across different subjects
  
  
  
  #shapes for gender
  shapes <- c("triangle", "circle", "square")
  V(net)$gender <- ifelse(V(net)$altgender_a == "Man (including transman and transmasculine)", 1,
                          ifelse(V(net)$altgender_a == "Woman (including transwoman and transfeminine)", 2, 3))
  V(net)$shape <- shapes[V(net)$gender]
  # Fruchterman-Reingold layout - trying to expand a bit not sure if this is working
  l <- layout_with_fr(net)
  #create a temporary png file
  # SimplePlot.file <- paste0("C:/Users/hochheic/OneDrive - The University of Colorado Denver/Helpers-Stay-Quit/03 Code/Network visualizations/visualization1_ID", i, ".png")
  SimplePlot.file  <- here("03 Code/Network visualizations", str_c("visualization1_ID", i, ".png"))

  png(filename = SimplePlot.file, width = 2200, height = 1400, res =100, units = "px",
      pointsize = 24)
  
  
  # expand margin on the right side for the legend
  par(mar=c(par("mar")[1:3], 10))
  
  # plot
  #  vertex.size = 15 changes the size of the nodes, but results in loss of information
  # for the betweeness measure
  plot(net, 
       vertex.size = V(net)$size, # CR added between_cen to adjust the size of the nodes according to betweeness measures
       layout = l*1, # original value was .25 
       vertex.label = V(net)$aname, 
       vertex.label.degree = pi/2, 
       vertex.label.dist = 0,
       ylim = c(-1, 1),
       xlim = c(-1, 1), 
       asp = 0)
  
  # add the first legend and save it's position
  l1 <- legend("topleft",
               legend = c("Smoker", "Non-smoker"),
               pch = 19, bty = "n",
               pt.cex = scaled[3],
               col = c("#f4a582", "#92c5de"),
               title = "Smoking status",
               xpd=TRUE, inset=c(1,0), title.adj=c(0))
  
  # add second legend and adjust x axis position based on height of first legend
  l2 <- legend(x = l1$rect$left, y = l1$rect$top - l1$rect$h,
               legend = c("Man", "Woman", "Different gender\nor declined"),
               pch = c(17, 19, 15), bty = "n",
               pt.cex = scaled[3], title.adj=c(0),
               title = "Gender", xpd = TRUE,
               inset = c(1,0))
    # add third legend and adjust x axis position based on height of second legend
  # col is the line color of the scale
  # pt.bg is the fill color
  legend(x = l2$rect$left, y = l2$rect$top - l2$rect$h,
         
         # Set the character labels for the scale of betweenness
         # legend=c(round(min(between_cen)), "",
         #          "", "", round(max(between_cen))),
         
         # Remove the character labels from the betweenness legend
         legend=c("", "","", "", ""),
         
         # Set the size of the betweenness circle indicators
         pt.cex= scaled3,
         
         # Additional legend characteristics
         col='black', pch=21, pt.bg='black', bty = "n",
         title = "Betweenness", xpd = TRUE,
         inset = c(1,0), title.adj=c(0))
  
  dev.off()
}

```

### Viz2
```{r visualization2}
# Degree centrality
#do we want an overall scale for degree centrality?
for(i in records){
  # i <- records[3]
  #select data for nodes and links
  nodes <- pna_baseline$alter %>% 
    filter(.egoID == i) %>% 
    select(-.egoID) %>% 
    rename(id = .altID)
  
  links <- pna_baseline$aatie %>% 
    filter(.egoID == i) %>% 
    select(-.egoID) %>%
    rename(from = .srcID, to = .tgtID,
           type = "weight") %>% 
    mutate(weight = dplyr::case_when(type == "Somewhat likely" ~ 1,
                                     type == "Very likely" ~ 4))
  
  #turn into an igraph object
  net <- graph_from_data_frame(d=links, vertices=nodes, directed=F) 
  graph <- as_tbl_graph(net)
  
  #set smoking colors 
  smoke_colors <- c("#92c5de", "#f4a582")
  V(net)$smokingstatus <- ifelse(V(net)$alttobacco_a == "No", 1, 2)
  V(net)$color <- smoke_colors[V(net)$smokingstatus]
  #weight for edges
  E(net)$width <- E(net)$weight
  
  #degree centrality will be used for the size - rescaling to be between 1-10
  degree_cen <- igraph::degree(net)
  V(net)$size <- scales::rescale(igraph::degree(net), to = c(5,15))
  
  #shapes for gender
  shapes <- c("triangle", "circle", "square")
  V(net)$gender <- ifelse(V(net)$altgender_a == "Man (including transman and transmasculine)", 1,
                          ifelse(V(net)$altgender_a == "Woman (including transwoman and transfeminine)", 2, 3))
  V(net)$shape <- shapes[V(net)$gender]
  
  # Fruchterman-Reingold layout - trying to expand a bit not sure if this is working
  l <- layout_with_fr(net)
  #create a temporary png file
  # SimplePlot.file <- paste0("C:/Users/hochheic/OneDrive - The University of Colorado Denver/Helpers-Stay-Quit/03 Code/Network visualizations/visualization2_ID", i, ".png")
  SimplePlot.file  <- here("03 Code/Network visualizations", str_c("visualization2_ID", i, ".png"))

  png(filename = SimplePlot.file, width = 2200, height = 1400, res =100, units = "px",
      pointsize = 24)
  # expand margin on the right side for the legend
  par(mar=c(par("mar")[1:3], 10))
  # plot
  plot(net, 
       layout = l*0.25, 
       vertex.label = V(net)$aname,
       ylim = c(-1, 1), 
       xlim = c(-1, 1), 
       asp = 0)
  
  # add the first legend and save it's position
  l1 <- legend("topleft",
               legend = c("Smoker", "Non-smoker"),
               pch = 19, bty = "n",
               pt.cex = scaled[3],
               col = c("#f4a582", "#92c5de"),
               title = "Smoking status",
               xpd=TRUE, inset=c(1,0), title.adj=c(0))
  
  # add second legend and adjust x axis position based on height of first legend
  l2 <- legend(x = l1$rect$left, y = l1$rect$top - l1$rect$h,
               legend = c("Man", "Woman", "Different gender\nor declined"),
               pch = c(17, 19, 15), bty = "n",
               pt.cex = scaled[3], title.adj=c(0),
               title = "Gender", xpd = TRUE,
               inset = c(1,0))
  # add third legend and adjust x axis position based on height of second legend
  legend(x = l2$rect$left, y = l2$rect$top - l2$rect$h,

         # legend=c(min(degree_cen), "",
         #          "", "", max(degree_cen)),
         # Remove the character labels from the betweenness legend
         legend=c("", "","", "", ""),
         
         pt.cex= scaled3,
         col='black',
         pch=21, 
         pt.bg='black', 
         bty = "n", # CR 12/11/2023 changed scaled3 to scaled[3]
         title = "Degree Centrality", xpd = TRUE,
         inset = c(1,0), title.adj=c(0))
  
  dev.off()
}

```

### Viz3
```{r visualization3}
# Closeness
#this is the same one we send through REDCap

# Set scaled 3 values
# *** Should not be needed since it's setup in viz1 section
# scaled3 <- seq(0.75, 3, length = 5)

# Set the scale so that it mimics viz1 and viz2
scaled4 <- seq(1, 4, length = 5)

for(i in records){
  # i <- records[3]
  #select data for nodes and links
  nodes <- pna_baseline$alter %>% 
    filter(.egoID == i) %>% 
    select(-.egoID) %>% 
    rename(id = .altID)
  
  links <- pna_baseline$aatie %>% 
    filter(.egoID == i) %>% 
    select(-.egoID) %>%
    rename(from = .srcID, to = .tgtID,
           type = "weight") %>% 
    mutate(weight = dplyr::case_when(type == "Somewhat likely" ~ 1,
                                     type == "Very likely" ~ 4))
  
  #turn into an igraph object
  net <- graph_from_data_frame(d=links, vertices=nodes, directed=F) 
  graph <- as_tbl_graph(net)
  
  #set smoking colors 
  smoke_colors <- c("#92c5de", "#f4a582")
  V(net)$smokingstatus <- ifelse(V(net)$alttobacco_a == "No", 1, 2)
  V(net)$color <- smoke_colors[V(net)$smokingstatus]
  #weight for edges
  E(net)$width <- E(net)$weight
  
  #betweenness will be used for the size - rescaling to be between 1-10
  #size for closeness
  V(net)$size <-ifelse(V(net)$altclose_a == "Not close at all", scaled4[1],
                                        ifelse(V(net)$altclose_a == "A little close", scaled4[2],
                                               ifelse(V(net)$altclose_a == "Somewhat close", scaled4[3],
                                                      ifelse(V(net)$altclose_a == "Quite close", scaled4[4],
                                                             scaled4[5]))))*3
  #shapes for gender
  shapes <- c("triangle", "circle", "square")
  V(net)$gender <- ifelse(V(net)$altgender_a == "Man (including transman and transmasculine)", 1,
                          ifelse(V(net)$altgender_a == "Woman (including transwoman and transfeminine)", 2, 3))
  V(net)$shape <- shapes[V(net)$gender]
  # Fruchterman-Reingold layout - trying to expand a bit not sure if this is working
  l <- layout_with_fr(net)
  #create a temporary png file
  # SimplePlot.file <- paste0("C:/Users/hochheic/OneDrive - The University of Colorado Denver/Helpers-Stay-Quit/03 Code/Network visualizations/visualization3_ID", i, ".png")
  SimplePlot.file  <- here("03 Code/Network visualizations", str_c("visualization3_ID", i, ".png"))

  png(filename = SimplePlot.file, width = 2200, height = 1400, res =100, units = "px",
      pointsize = 24)
  # expand margin on the right side for the legend
  par(mar=c(par("mar")[1:3], 10))
  # plot
  plot(net, layout = l*0.25, vertex.label = V(net)$aname,
       ylim = c(-1, 1), xlim = c(-1, 1), asp = 0)
  # add the first legend and save it's position
  l1 <- legend("topleft",
               legend = c("Smoker", "Non-smoker"),
               pch = 19, bty = "n",
               pt.cex = scaled[3],
               col = c("#f4a582", "#92c5de"),
               title = "Smoking status",
               xpd=TRUE, inset=c(1,0), title.adj=c(0))
  
  # add second legend and adjust x axis position based on height of first legend
  l2 <- legend(x = l1$rect$left, y = l1$rect$top - l1$rect$h,
               legend = c("Man", "Woman", "Different gender\nor declined"),
               pch = c(17, 19, 15), bty = "n",
               pt.cex = scaled[3], title.adj=c(0),
               title = "Gender", xpd = TRUE,
               inset = c(1,0))
  # add third legend and adjust x axis position based on height of second legend
  legend(x = l2$rect$left, y = l2$rect$top - l2$rect$h,
         legend=c("Not close at all", "A little close",
                  "Somewhat close", "Quite close", "Very close"),
         pt.cex= scaled3,col='black',pch=21, pt.bg='black', bty = "n",
         title = "How close to you", xpd = TRUE,
         inset = c(1,0), title.adj=c(0))
  
  dev.off()
}

```

### Viz4
```{r visualization4}
# Frequency of interaction

# scaled4 <- seq(0.75, 3, length = 5)

# Set the scale so that it mimics viz1 and viz2
scaled4 <- seq(2, 7, length = 5)

for(i in records){
  # i <- records[3]
  #select data for nodes and links
  nodes <- pna_baseline$alter %>% 
    filter(.egoID == i) %>% 
    select(-.egoID) %>% 
    rename(id = .altID)
  
  links <- pna_baseline$aatie %>% 
    filter(.egoID == i) %>% 
    select(-.egoID) %>%
    rename(from = .srcID, to = .tgtID,
           type = "weight") %>% 
    mutate(weight = dplyr::case_when(type == "Somewhat likely" ~ 1,
                                     type == "Very likely" ~ 4))
  
  #turn into an igraph object
  net <- graph_from_data_frame(d=links, vertices=nodes, directed=F) 
  graph <- as_tbl_graph(net)
  
  #set smoking colors 
  smoke_colors <- c("#92c5de", "#f4a582")
  V(net)$smokingstatus <- ifelse(V(net)$alttobacco_a == "No", 1, 2)
  V(net)$color <- smoke_colors[V(net)$smokingstatus]
  
  #weight for edges
  E(net)$width <- E(net)$weight
  
  #betweenness will be used for the size - rescaling to be between 1-10
  #size for frequency of interaction
  V(net)$size <- ifelse(V(net)$altintfreq_a == "Once a year or so", scaled4[1],
                                        ifelse(V(net)$altintfreq_a == "At least once every several months", scaled4[2],
                                               ifelse(V(net)$altintfreq_a == "At least once a month", scaled4[3],
                                                      ifelse(V(net)$altintfreq_a == "At least once a week", scaled4[4],
                                                             scaled4[5]))))*2
  #shapes for gender
  shapes <- c("triangle", "circle", "square")
  V(net)$gender <- ifelse(V(net)$altgender_a == "Man (including transman and transmasculine)", 1,
                          ifelse(V(net)$altgender_a == "Woman (including transwoman and transfeminine)", 2, 3))
  V(net)$shape <- shapes[V(net)$gender]
  # Fruchterman-Reingold layout - trying to expand a bit not sure if this is working
  l <- layout_with_fr(net)
  #create a temporary png file
  # SimplePlot.file <- paste0("C:/Users/hochheic/OneDrive - The University of Colorado Denver/Helpers-Stay-Quit/03 Code/Network visualizations/visualization4_ID", i, ".png")
  SimplePlot.file  <- here("03 Code/Network visualizations", str_c("visualization4_ID", i, ".png"))

  png(filename = SimplePlot.file, width = 2200, height = 1400, res =100, units = "px",
      pointsize = 24)
  # expand margin on the right side for the legend
  par(mar=c(par("mar")[1:3], 10))
  # plot
  plot(net, layout = l*0.25, vertex.label = V(net)$aname,
       ylim = c(-1, 1), xlim = c(-1, 1), asp = 0)
  # add the first legend and save it's position
  l1 <- legend("topleft",
               legend = c("Smoker", "Non-smoker"),
               pch = 19, bty = "n",
               pt.cex = scaled[3],
               col = c("#f4a582", "#92c5de"),
               title = "Smoking status",
               xpd=TRUE, inset=c(1,0), title.adj=c(0))
  
  # add second legend and adjust x axis position based on height of first legend
  l2 <- legend(x = l1$rect$left, y = l1$rect$top - l1$rect$h,
               legend = c("Man", "Woman", "Different gender\nor declined"),
               pch = c(17, 19, 15), bty = "n",
               pt.cex = scaled[3], title.adj=c(0),
               title = "Gender", xpd = TRUE,
               inset = c(1,0))
  # add third legend and adjust x axis position based on height of second legend
  legend(x = l2$rect$left, y = l2$rect$top - l2$rect$h,
         legend=c("Once a year or so", "At least once every\nseveral months",
                  "At least once a month", "At least once a week", "Almost every day"),
         pt.cex= scaled3,col='black',pch=21, pt.bg='black', bty = "n",
         title = "How frequently you interact", xpd = TRUE,
         inset = c(1,0), title.adj=c(0))
  
  dev.off()
}

```

### Viz5
```{r visualization5}
# scaled5 <- c(0.5, 0.75, 1, 2, 3)

scaled5 <- seq(2, 7, length = 5)


for(i in records){
  # i <- records[1]
  #select data for nodes and links
  nodes <- pna_baseline$alter %>% 
    filter(.egoID == i) %>% 
    select(-.egoID) %>% 
    rename(id = .altID)
  
  links <- pna_baseline$aatie %>% 
    filter(.egoID == i) %>% 
    select(-.egoID) %>%
    rename(from = .srcID, to = .tgtID,
           type = "weight") %>% 
    mutate(weight = dplyr::case_when(type == "Somewhat likely" ~ 1,
                                     type == "Very likely" ~ 4))
  
  #turn into an igraph object
  net <- graph_from_data_frame(d=links, vertices=nodes, directed=F) 
  graph <- as_tbl_graph(net)
  
  #set smoking colors 
  smoke_colors <- c("#92c5de", "#f4a582")
  V(net)$smokingstatus <- ifelse(V(net)$alttobacco_a == "No", 1, 2)
  V(net)$color <- smoke_colors[V(net)$smokingstatus]
  #weight for edges
  E(net)$width <- E(net)$weight
  #betweenness will be used for the size - rescaling to be between 1-10
  #size for age
  V(net)$size <- ifelse(V(net)$altage_a == "Don't know", scaled5[1],
                                        ifelse(V(net)$altage_a == "12 or Under", scaled5[2],
                                               ifelse(V(net)$altage_a == "13 - 17", scaled5[3],
                                                      ifelse(V(net)$altage_a == "18 - 64", scaled5[4],
                                                             scaled5[5]))))*2
  #shapes for gender
  shapes <- c("triangle", "circle", "square")
  V(net)$gender <- ifelse(V(net)$altgender_a == "Man (including transman and transmasculine)", 1,
                          ifelse(V(net)$altgender_a == "Woman (including transwoman and transfeminine)", 2, 3))
  V(net)$shape <- shapes[V(net)$gender]
  # Fruchterman-Reingold layout - trying to expand a bit not sure if this is working
  l <- layout_with_fr(net)
  #create a temporary png file
  # SimplePlot.file <- paste0("C:/Users/hochheic/OneDrive - The University of Colorado Denver/Helpers-Stay-Quit/03 Code/Network visualizations/visualization5_ID", i, ".png")
  SimplePlot.file  <- here("03 Code/Network visualizations", str_c("visualization5_ID", i, ".png"))

  png(filename = SimplePlot.file, width = 2200, height = 1400, res =100, units = "px",
      pointsize = 24)
  # expand margin on the right side for the legend
  par(mar=c(par("mar")[1:3], 10))
  # plot
  plot(net, layout = l*0.25, vertex.label = V(net)$aname,
       ylim = c(-1, 1), xlim = c(-1, 1), asp = 0)
  # add the first legend and save it's position
  l1 <- legend("topleft",
               legend = c("Smoker", "Non-smoker"),
               pch = 19, bty = "n",
               pt.cex = scaled[3],
               col = c("#f4a582", "#92c5de"),
               title = "Smoking status",
               xpd=TRUE, inset=c(1,0), title.adj=c(0))
  
  # add second legend and adjust x axis position based on height of first legend
  l2 <- legend(x = l1$rect$left, y = l1$rect$top - l1$rect$h,
               legend = c("Man", "Woman", "Different gender\nor declined"),
               pch = c(17, 19, 15), bty = "n",
               pt.cex = scaled[3], title.adj=c(0),
               title = "Gender", xpd = TRUE,
               inset = c(1,0))
  # add third legend and adjust x axis position based on height of second legend
  legend(x = l2$rect$left, y = l2$rect$top - l2$rect$h,
         legend=c("Don't know", "12 or Under",
                  "13 - 17", "18 - 64", "65 or older"),
         pt.cex= scaled3,col='black',pch=21, pt.bg='black', bty = "n",
         title = "Age", xpd = TRUE,
         inset = c(1,0), title.adj=c(0))
  
  dev.off()
}

```
